---
- stat:
    path: "{{ deb_resolv }}"
  register: etc_resolvconf
  become: true

- name: Conserve une copie du fichier resolv.conf
  command: mv {{ deb_resolv }} {{ bak_resolv }}
  become: true
  when: etc_resolvconf.stat.exists == True

- stat:
    path: "{{ deb_resolv }}"
  register: etc_resolvconf
  become: true

- name: Copie du modèle resolv.conf vers les serveurs distants
  template:
    src: "{{ src_resolv }}"
    dest: "{{ deb_resolv }}"
    force: yes
  become: true
  when: etc_resolvconf.stat.exists == False

- name: Modifie resolv.conf avec Network-Manager (centOS)
  blockinfile:
    path: "{{centos_ifcfg_file}}-{{ ansible_default_ipv4.interface }}"
    insertafter: "{{ old_dns }}"
    block: "{{ add_dns }}"
  when: ansible_os_family == 'RedHat'
  become: true

- name: Supprime la derniere ligne du fichier ifcfg-<int>
  lineinfile:
    path: "{{centos_ifcfg_file}}-{{ ansible_default_ipv4.interface }}"
    line: "{{ old_dns }}"
    state: absent
  when: ansible_os_family == 'RedHat'
  become: true


- name: Redémarre l'interface réseau (centOS)
  #service: network restart ### Conflit avec Network-Manager
  command: "{{ initd_netw }} restart"
  when: ansible_os_family == 'RedHat'
  become: true
