---
- name: Installation des serveurs dns bind
  hosts: dnsservers
  remote_user: esgi
  become_user: root

  roles:
    - sources
    - sudo
    - ssh
    - utils
    - firewall
    - resolv
    - bind-default

- import_playbook: playbook-master.yml
- import_playbook: playbook-slave.yml
- import_playbook: playbook-check.yml
...
