---
- stat:
    path: "{{ deb_sourceslist }}"
  register: apt_sourceslist
- name: Conserve une copie du fichier sources.list (Debian)
  command: mv {{ deb_sourceslist }} {{ bak_sourceslist }}
  become_method: su
  become: true
  when: apt_sourceslist.stat.exists == True and ansible_os_family == 'Debian'

- stat:
    path: "{{ deb_sourceslist }}"
  register: apt_sourceslist
- name: Copie du modèle sources.list vers les serveurs distants (Debian)
  template:
    src: "{{ src_sourceslist }}"
    dest: "{{ deb_sourceslist }}"
    force: yes
  become_method: su
  become: true
  when: apt_sourceslist.stat.exists == False and ansible_os_family == 'Debian'

- name: Mise à jour des repositories apt (Debian)
  #apt: update_cache=yes ### Timeout si script rejoué
  command: apt-get update
  become_method: su
  become: true
  when: ansible_os_family == 'Debian'


- name: Modifie les paramètres de l'interface ethernet (centOS)
  lineinfile:
    path: "{{centos_ifcfg_file}}-{{ ansible_default_ipv4.interface }}"
    line: "{{ DNS1 }}"
  when: ansible_os_family == 'RedHat'
  become_method: su
  become: true

- name: Redémarre l'interface réseau (centOS)
  #service: network restart ### Conflit avec Network-Manager
  command: "{{ initd_netw }} restart"
  when: ansible_os_family == 'RedHat'
  become_method: su
  become: true
