---
- name: Ajout de la clé SSH
  when: deploy_user is defined
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become_method: su
  become: true

- name: "{{ deploy_user }} devient sudoer"
  when: deploy_user is defined
  template:
    src: "{{ src_sudoers }}"
    dest: "{{ dir_sudoers }}/{{ deploy_user }}-sudoer"
  #  validate: visudo -cf %s ### Bug déclaré: Ne prend pas en compte 'become:'
  become_method: su
  become: true

- name: Désactive accès SSH pour root
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "{{ regex_permrootlog }}"
    line: "{{ permit_no }}"
    state: present
  become: true

- name: Restart SSH
# bug du service SSH depuis ansible 1.9.1: https://github.com/ansible/ansible-modules-core/issues/1533
  shell: sleep 3; /etc/init.d/sshd restart
  async: 1
  poll: 0
  become: true
