---
- stat:
    path: "{{ namedfile_local }}"
  register: namedconf_local
  become: true

- name: Copie du modèle named.conf.local vers le serveur slave
  template:
    src: "{{ src_namedfile_local }}"
    dest: "{{ namedfile_local }}"
    force: yes
  become: true
  when: namedconf_local.stat.exists == False

- name: "{{ bind_user }} propriétaire du répertoire {{ bind_dir }}"
  file:
    path: "{{ bind_dir }}"
    recurse: yes
    mode: "{{ umask }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_group }}"
  become: true
  notify: bind9 reload
