---
- name: Installation des paquets de base (Debian)
  apt:
    name: "{{ deb_pkg }}"
    state: latest
  become: true
  with_items: "{{ deb_pkg }}"
  when: ansible_os_family == "Debian"

- name: Installation des paquets de base (CentOS)
  yum:
    name: "{{ centos_pkg }}"
    state: latest
  become: true
  with_items: "{{ centos_pkg }}"
  when: ansible_os_family == "RedHat"
