---
- name: Verification des logs (CentOS)
  shell: |
    sleep 6; cat {{ centos_log }}
  become: true
  register: resultat
  when: "'slave_host' in group_names and ansible_os_family == 'RedHat'"

- stat:
    path: "{{ centos_log }}"
  register: log_messages
- name: Status du transfert de zones (CentOS)
  when: "'slave_host' in group_names and ansible_os_family == 'RedHat' and log_messages.stat.exists == True and resultat.stdout.find('Transfer completed') >= 1"
  debug:
    msg: "Transfer status success - Transfert de zones correctement configuré"

- name: Verification des logs (Debian)
  shell: |
    sleep 6; cat {{ deb_log }}
  become: true
  register: resultat
  when: "'slave_host' in group_names and ansible_os_family == 'Debian'"

- stat:
    path: "{{ deb_log }}"
  register: log_syslog
- name: Status du transfert de zones (Debian)
  when: "'slave_host' in group_names and ansible_os_family == 'Debian' and log_syslog.stat.exists == True and resultat.stdout.find('Transfer completed') >= 1"
  debug:
    msg: "Transfer status success - Transfert de zones correctement configuré"

- stat:
    path: "{{ centos_db_dom_lan }}"
  register: dom_lan
  become: true
- name: "Vérifie la présence du fichier {{ file_dom_lan }} sur slave (CentOS)"
  when: "'slave_host' in group_names and dom_lan.stat.exists == True and ansible_os_family == 'RedHat'"
  debug:
    msg: "Transfert du fichier de zone {{ file_dom_lan }} réussi"

- stat:
    path: "{{ centos_db_dom_lan_inv }}"
  register: dom_lan_inv
  become: true
- name: "Vérifie la présence du fichier {{ file_dom_lan_inv }} sur slave (CentOS)"
  when: "'slave_host' in group_names and dom_lan_inv.stat.exists == True and ansible_os_family == 'RedHat'"
  debug:
    msg: "Transfert du fichier de zone {{ file_dom_lan_inv }} réussi"

- stat:
    path: "{{ deb_db_dom_lan }}"
  register: dom_lan
  become: true
- name: "Vérifie la présence du fichier {{ file_dom_lan }} sur slave (Debian)"
  when: "'slave_host' in group_names and dom_lan.stat.exists == True and ansible_os_family == 'Debian'"
  debug:
    msg: "Transfert du fichier de zone {{ file_dom_lan }} réussi"

- stat:
    path: "{{ deb_db_dom_lan_inv }}"
  register: dom_lan_inv
  become: true
- name: "Vérifie la présence du fichier {{ file_dom_lan_inv }} sur slave (Debian)"
  when: "'slave_host' in group_names and dom_lan_inv.stat.exists == True and ansible_os_family == 'Debian'"
  debug:
    msg: "Transfert du fichier de zone {{ file_dom_lan_inv }} réussi"
